[package]
name = "fleetos-ebpf"
version = "0.1.1"
edition = "2024"
license = "Apache-2.0"
authors = ["Philip Aster and the FleetOS Contributors"]
description = "FleetOS eBPF Kernel Level Enforcement and Routing Plane"

[dependencies]
aya-ebpf = "0.2.1"
# Added fleetos-ebpf-common to resolve ABI Divergence blocker
fleetos-ebpf-common = { path = "../fleetos-ebpf-common", default-features = false }

[[bin]]
name = "fleetos-ebpf"
path = "src/main.rs"
